version: '3.8'
services:
  app:
    image: sample-image:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hibeat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 121
    depends_on:
      - db
  db:
    image: postgres
    environment:
        POSTGRES_DB: hibeat
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 121
